repos:
  - repo: local
    hooks:
      - id: check-broken-symlinks
        name: Check for broken symlinks
        entry: custom-hooks/check-broken-symlinks
        language: system
        types: [file]
      - id: check-docstring-length
        name: Check docstring length
        entry: custom-hooks/check-docstring-length
        language: system
        types: [file]
